begin;
select plan(1);
select set_config('jobpilot.test.owner',(select id::text from auth.users order by created_at limit 1 offset 1),true);
select set_config('jobpilot.test.other',(select id::text from auth.users order by created_at limit 1),true);
set local role service_role;
do $$ declare u uuid:=current_setting('jobpilot.test.owner')::uuid; other uuid:=current_setting('jobpilot.test.other')::uuid; checkout uuid:=gen_random_uuid(); token uuid:=gen_random_uuid();begin
 insert into public.recruiter_companies(user_id,name,domain,contact_name,contact_email,website,verification_status) values(u,'Recovery Test','recover.example','Owner','owner@recover.example','https://recover.example','verified');
 perform public.begin_billing_checkout(u,checkout,'posting_five','test');
 begin perform public.recover_billing_checkout(other,checkout,'plink_fixture',null,'https://rzp.io/fixture');raise exception 'Foreign recovery allowed';exception when raise_exception then if sqlerrm<>'checkout_conflict' then raise;end if;end;
 begin perform public.recover_billing_checkout(u,checkout,'sub_fixture','plan_fixture','https://rzp.io/fixture');raise exception 'Wrong product recovery allowed';exception when raise_exception then if sqlerrm<>'checkout_conflict' then raise;end if;end;
 perform public.recover_billing_checkout(u,checkout,'plink_fixture',null,'https://rzp.io/fixture');
 perform public.recover_billing_checkout(u,checkout,'plink_fixture',null,'https://rzp.io/fixture');
 if (select count(*) from public.billing_events where intent_id=checkout)<>1 then raise exception 'Recovery not idempotent';end if;
 begin perform public.recover_billing_checkout(u,checkout,'plink_otherref',null,'https://rzp.io/fixture');raise exception 'Recovery overwrote resource';exception when raise_exception then if sqlerrm<>'checkout_conflict' then raise;end if;end;
 perform public.claim_billing_event(checkout,token,'event_captured');perform public.apply_billing_snapshot(checkout,token,'event_captured','paid','pay_fixture',199900,0,now(),null,null);
 perform public.claim_billing_event(checkout,token,'event_disputed');
 begin perform public.apply_billing_dispute(checkout,null,'disp_fixture','pay_fixture','open',100);raise exception 'Unleased dispute allowed';exception when raise_exception then if sqlerrm<>'billing_busy' then raise;end if;end;
 begin perform public.apply_billing_dispute(checkout,token,'disp_fixture','pay_fixture','open',200000);raise exception 'Dispute amount exceeded payment';exception when raise_exception then if sqlerrm<>'invalid_dispute' then raise;end if;end;
 perform public.apply_billing_dispute(checkout,token,'disp_fixture','pay_fixture','open',100);
 perform public.apply_billing_snapshot(checkout,token,'event_disputed','paid','pay_fixture',199900,0,now(),null,null);
 if not (select disputed from public.billing_intents where id=checkout) or (select balance from public.posting_credit_balance where user_id=u and mode='test')<>0 then raise exception 'Disputed credits restored';end if;
 perform public.claim_billing_event(checkout,token,'event_repeated');perform public.apply_billing_snapshot(checkout,token,'event_repeated','paid','pay_fixture',199900,0,now(),null,null);
 if (select balance from public.posting_credit_balance where user_id=u and mode='test')<>0 then raise exception 'Payment replay bypassed dispute';end if;
 perform public.claim_billing_event(checkout,token,'event_two_disputes');perform public.apply_billing_dispute(checkout,token,'disp_otherref','pay_fixture','lost',100);perform public.apply_billing_dispute(checkout,token,'disp_fixture','pay_fixture','won',100);perform public.apply_billing_snapshot(checkout,token,'event_two_disputes','paid','pay_fixture',199900,0,now(),null,null);
 if (select balance from public.posting_credit_balance where user_id=u and mode='test')<>0 then raise exception 'One won dispute cleared another';end if;
 perform public.claim_billing_event(checkout,token,'event_all_won');perform public.apply_billing_dispute(checkout,token,'disp_otherref','pay_fixture','won',100);perform public.apply_billing_snapshot(checkout,token,'event_all_won','paid','pay_fixture',199900,0,now(),null,null);
 if (select disputed from public.billing_intents where id=checkout) or (select balance from public.posting_credit_balance where user_id=u and mode='test')<>5 then raise exception 'Won dispute did not restore verified purchase';end if;
 perform public.begin_billing_checkout(other,gen_random_uuid(),'candidate_pro','live');
 begin insert into public.account_deletion_requests(user_id) values(other);raise exception 'Live mandate owner deletion allowed';exception when raise_exception then if sqlerrm<>'subscription_active' then raise;end if;end;
 update public.billing_intents set status='cancelled' where user_id=other and mode='live';
 insert into public.account_deletion_requests(user_id) values(other);
end $$;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('jobpilot.test.other'),'role','authenticated')::text,true);
do $$ begin
 if exists(select 1 from public.billing_disputes) then raise exception 'Foreign dispute visible';end if;
 begin update public.billing_disputes set status='won';raise exception 'Browser cleared dispute';exception when insufficient_privilege then null;end;
 begin perform public.recover_billing_checkout(auth.uid(),gen_random_uuid(),'plink_fixture',null,'https://rzp.io/fixture');raise exception 'Browser recovered checkout';exception when insufficient_privilege then null;end;
end $$;
select pass('Recovery is owner-bound and idempotent; disputes require a lease, freeze grants, resist paid replays, remain blocked across multiple cases and are browser-private');
select * from finish();
rollback;
