begin;
select plan(1);
select set_config('jobpilot.test.actor',(select id::text from auth.users order by created_at limit 1),true);
select set_config('jobpilot.test.target',(select id::text from auth.users order by created_at limit 1 offset 1),true);
set local role service_role;
do $$ declare u uuid:=current_setting('jobpilot.test.target')::uuid; candidate uuid:=current_setting('jobpilot.test.actor')::uuid; company uuid; pack uuid:=gen_random_uuid(); sub uuid:=gen_random_uuid(); token uuid:=gen_random_uuid(); checkout jsonb; job uuid; fields jsonb:='{"title":"Engineer","description":"Build and maintain reliable software with a collaborative engineering team.","location":"Remote","country":"India","employment_type":"full-time","seniority":"senior","salary_currency":"INR","skills":["React"],"application_url":"https://revenue.example/apply","posting_status":"draft"}';begin
 if (select paid_access from public.billing_policy where singleton) then raise exception 'Launch payment gate enabled';end if;
 insert into public.recruiter_companies(user_id,name,domain,contact_name,contact_email,website,verification_status) values(u,'Revenue Test','revenue.example','Owner','owner@revenue.example','https://revenue.example','verified') returning id into company;
 checkout:=public.begin_billing_checkout(u,pack,'posting_five','test');
 if not (checkout->>'new')::boolean then raise exception 'New checkout missing';end if;
 if (public.begin_billing_checkout(u,gen_random_uuid(),'posting_five','test')->>'new')::boolean then raise exception 'Duplicate external create allowed';end if;
 begin perform public.begin_billing_checkout(candidate,pack,'candidate_pro','test');raise exception 'Foreign checkout accepted';exception when raise_exception then if sqlerrm<>'checkout_conflict' then raise;end if;end;
 update public.billing_intents set provider_resource='plink_fixture',status='created' where id=pack;
 begin perform public.apply_billing_snapshot(pack,null,'event_unleased','paid','pay_fixture',199900,0,now(),null,null);raise exception 'Absent lease accepted';exception when raise_exception then if sqlerrm<>'billing_busy' then raise;end if;end;
 perform public.claim_billing_event(pack,token,'event_paid');
 begin perform public.apply_billing_snapshot(pack,token,'event_paid','paid','pay_fixture',1,0,now(),null,null);raise exception 'Forged price accepted';exception when raise_exception then if sqlerrm<>'invalid_payment' then raise;end if;end;
 perform public.apply_billing_snapshot(pack,token,'event_paid','paid','pay_fixture',199900,0,now(),null,null);
 if (select balance from public.posting_credit_balance where user_id=u and mode='test')<>5 then raise exception 'Credits not granted';end if;
 if public.claim_billing_event(pack,token,'event_paid') then raise exception 'Duplicate event reprocessed';end if;
 update public.billing_products set credits=20 where id='posting_five';
 perform public.claim_billing_event(pack,token,'event_refund');perform public.apply_billing_snapshot(pack,token,'event_refund','refunded','pay_fixture',199900,100,now(),null,null);
 if (select balance from public.posting_credit_balance where user_id=u and mode='test')<>0 then raise exception 'Refund did not reverse snapshot credits';end if;
 perform public.claim_billing_event(pack,token,'event_replay');perform public.apply_billing_snapshot(pack,token,'event_replay','paid','pay_fixture',199900,0,now(),null,null);
 if (select balance from public.posting_credit_balance where user_id=u and mode='test')<>0 or (select refunded_minor from public.billing_payments where id='pay_fixture')<>100 then raise exception 'Older payment resurrected credits';end if;
 checkout:=public.begin_billing_checkout(candidate,sub,'candidate_pro','test');update public.billing_intents set provider_resource='sub_fixture',provider_plan='plan_fixture' where id=sub;
 perform public.claim_billing_event(sub,token,'event_subscription');perform public.apply_billing_snapshot(sub,token,'event_subscription','active','pay_subfixture',29900,0,now(),now()+interval '30 days',null);
 if public.effective_launch_plan(candidate)->>'id'<>'free_launch' then raise exception 'Test payment upgraded production';end if;
 update public.billing_entitlements set active=false where user_id=candidate;
 perform public.claim_billing_event(sub,token,'event_old_cycle');perform public.apply_billing_snapshot(sub,token,'event_old_cycle','active','pay_oldfixture',29900,0,now()-interval '40 days',now()-interval '10 days',null);
 if (select active from public.billing_entitlements where user_id=candidate) then raise exception 'Old paid cycle resurrected access';end if;
 update public.billing_entitlements set active=true where user_id=candidate;
 update public.billing_entitlements set mode='live' where user_id=candidate;
 if public.effective_launch_plan(candidate)->>'id'<>'candidate_pro' then raise exception 'Live entitlement not applied';end if;
 perform public.set_candidate_visibility(candidate,0,true,false,null,false,true);
 if not (public.search_hiring_candidates(u,null,null,null,null,0,false)->0->>'featured')::boolean then raise exception 'Pro featured consent missing';end if;
 update public.billing_entitlements set expires_at=now()-interval '1 second' where user_id=candidate;
 if (public.search_hiring_candidates(u,null,null,null,null,0,false)->0->>'featured')::boolean then raise exception 'Expired featured badge retained';end if;
 job:=public.save_recruiter_job(u,company,null,0,fields);
 update public.billing_policy set paid_access=true;
 begin perform public.search_hiring_candidates(u,null,null,null,null,0,false);raise exception 'Unpaid database access';exception when raise_exception then if sqlerrm<>'database_plan_required' then raise;end if;end;
 begin perform public.save_recruiter_job(u,company,job,1,fields||'{"posting_status":"published"}');raise exception 'Test credits spent live';exception when raise_exception then if sqlerrm<>'posting_credit_required' then raise;end if;end;
 insert into public.posting_credit_balance(user_id,mode,balance) values(u,'live',1);
 perform public.save_recruiter_job(u,company,job,1,fields||'{"posting_status":"published"}');
 perform public.save_recruiter_job(u,company,job,2,fields||'{"posting_status":"paused"}');
 perform public.save_recruiter_job(u,company,job,3,fields||'{"posting_status":"published"}');
 if (select balance from public.posting_credit_balance where user_id=u and mode='live')<>0 or (select count(*) from public.posting_credit_spends where job_id=job)<>1 then raise exception 'Publication charged twice';end if;
end $$;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('jobpilot.test.actor'),'role','authenticated')::text,true);
do $$ begin
 if exists(select 1 from public.billing_payments where user_id<>auth.uid()) then raise exception 'Foreign billing exposed';end if;
 begin select lease_token from public.billing_intents;raise exception 'Billing lease exposed';exception when insufficient_privilege then null;end;
 begin update public.posting_credit_balance set balance=999;raise exception 'Browser minted credits';exception when insufficient_privilege then null;end;
 begin perform public.begin_billing_checkout(auth.uid(),gen_random_uuid(),'candidate_pro','live');raise exception 'Browser checkout RPC';exception when insufficient_privilege then null;end;
end $$;
select pass('Billing is owner-private and service-only; amounts, deduplication, immutable refunds, snapshot credits, test/live isolation, featured expiry, paid search and single credit spending are enforced');
select * from finish();
rollback;
