import type { Credential } from "./model.ts";

const escape = (value: string) => value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character]!);

export function completionHtml(credential: Credential, name: string, verificationUrl: string) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>JobPilot completion record</title><style>
  @page{size:A4 landscape;margin:18mm}*{box-sizing:border-box}body{margin:0;padding:32px;font:16px/1.6 system-ui,sans-serif;color:#172033;background:#f7f9fc}main{max-width:960px;margin:auto;padding:48px;border:2px solid #6474e5;background:white}h1{font-size:36px;line-height:1.2}h2{font-size:26px}small{display:block;color:#526078}.label{letter-spacing:2px;text-transform:uppercase;color:#526078}.meta{overflow-wrap:anywhere}@media print{body{padding:0;background:white}.print-tip{display:none}main{padding:24px}h1{font-size:30px}}
  </style></head><body><p class="print-tip">Use your browser's Print → Save as PDF. This is a JobPilot record, not a provider certificate.</p><main><p class="label">JobPilot · SkillPath</p><h1>Learning-path completion</h1><p>This records completion by</p><h2>${escape(name || "JobPilot learner")}</h2><p>of the original short learning path</p><h2>${escape(credential.title)}</h2><p>Issued ${escape(credential.issued_on)}</p><p>Includes self-reported lesson exercises, a passed three-question knowledge check (at least 2 correct), and a self-reported project submission.</p><small>Issued by JobPilot. Not accredited, not identity-verified, not an external provider credential, and not proof of employment or independently assessed project quality. No affiliation with resource providers is implied.</small><p class="meta">Record ID: ${escape(credential.id)}</p>${credential.is_public ? `<p class="meta">Public verification: ${escape(verificationUrl)}</p>` : "<small>Private record. Public verification is disabled until you explicitly enable sharing in My credentials.</small>"}</main></body></html>`;
}
