'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
type Review={id:string;version:number;status:string;details:string;evidence_url:string;review_note:string|null;created_at:string;recruiter_companies:{name:string;domain:string;website:string;contact_name:string;contact_email:string;corporate_email_verified:boolean;verification_status:string}};
export default function CompanyVerificationsPage(){
  const [rows,setRows]=useState<Review[]>([]),[offset,setOffset]=useState(0),[hasMore,setHasMore]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[notes,setNotes]=useState<Record<string,string>>({});const lock=useRef(false);
  const load=useCallback(async(page:number)=>{const response=await fetch(`/api/admin/company-verifications?offset=${page}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);setRows(data.requests);setHasMore(data.has_more);},[]);
  useEffect(()=>{let stopped=false;(async()=>{try{const response=await fetch(`/api/admin/company-verifications?offset=${offset}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);if(!stopped){setRows(data.requests);setHasMore(data.has_more);setError('');}}catch(cause){if(!stopped)setError((cause as Error).message);}finally{if(!stopped)setLoading(false);}})();return()=>{stopped=true;};},[offset]);
  async function review(row:Review,decision:string){if(lock.current)return;if(decision==='approved'&&!window.confirm('Approve this company only after reviewing its identity, evidence and hiring authority. Approval permits public job posting.'))return;if(decision==='revoked'&&!window.confirm('Revoke company verification and pause all published jobs?'))return;
    lock.current=true;setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/admin/company-verifications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id,version:row.version,decision,note:notes[row.id]||''})});const data=await response.json();if(!response.ok)throw Error(data.error);await load(offset);setMessage('Company review saved.');}catch(cause){setError((cause as Error).message);}finally{lock.current=false;setBusy(false);}}
  return <div className="mx-auto max-w-5xl space-y-5 p-5 sm:p-8"><header><h1 className="text-2xl font-bold">Company verification queue</h1><p className="mt-2 text-sm text-muted-foreground">Admin review of company identity and hiring authority. Evidence and corporate contact information stay private.</p></header>{loading&&<p role="status">Loading requests…</p>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{message&&<p role="status" className="text-sm">{message}</p>}
    {!loading&&!error&&rows.length===0&&<p className="rounded-xl border p-5 text-sm">No company verification requests.</p>}
    {rows.map(row=><article key={row.id} className="rounded-2xl border bg-background p-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{row.recruiter_companies.name}</h2><span className="text-xs">Request {row.status} · Company {row.recruiter_companies.verification_status}</span></div><p className="mt-2 text-sm">{row.recruiter_companies.contact_name} · {row.recruiter_companies.contact_email}</p><p className="mt-1 text-xs text-muted-foreground">Corporate email {row.recruiter_companies.corporate_email_verified?'confirmed and matched':'not matched — independent business evidence required'} · {row.recruiter_companies.domain}</p><p className="mt-3 whitespace-pre-wrap text-sm">{row.details}</p><div className="mt-3 flex gap-4 text-sm"><a className="text-primary underline" href={row.recruiter_companies.website} target="_blank" rel="noopener noreferrer">Company website ↗</a><a className="text-primary underline" href={row.evidence_url} target="_blank" rel="noopener noreferrer">Business evidence ↗</a></div>{row.review_note&&<p className="mt-3 whitespace-pre-wrap text-sm text-muted-foreground">Review: {row.review_note}</p>}
      {['pending','approved'].includes(row.status)&&<><label className="mt-4 block text-sm" htmlFor={`review-${row.id}`}>Decision note (required)</label><textarea id={`review-${row.id}`} className="mt-1 w-full rounded-lg border bg-background p-3 text-sm" rows={3} minLength={10} maxLength={2000} disabled={busy} value={notes[row.id]||''} onChange={event=>setNotes({...notes,[row.id]:event.target.value})}/><div className="mt-3 flex flex-wrap gap-2">{(row.status==='pending'?['approved','rejected']:['revoked']).map(decision=><Button key={decision} variant="outline" disabled={busy||(notes[row.id]||'').trim().length<10} onClick={()=>void review(row,decision)}>{decision==='approved'?'Approve company':decision==='rejected'?'Reject request':'Revoke verification'}</Button>)}</div></>}
    </article>)}
    <div className="flex gap-3"><Button variant="outline" disabled={busy||loading||offset===0} onClick={()=>{setLoading(true);setOffset(Math.max(0,offset-50));}}>Previous</Button><Button variant="outline" disabled={busy||loading||!hasMore} onClick={()=>{setLoading(true);setOffset(offset+50);}}>Next</Button><Button variant="outline" disabled={busy||loading} onClick={()=>void load(offset).catch(cause=>setError(cause.message))}>Refresh</Button></div>
  </div>;
}
