import test from 'node:test';import assert from 'node:assert/strict';import { Module } from 'node:module';import { readFileSync } from 'node:fs';import ts from 'typescript';import { createECDH } from 'node:crypto';
import * as reminders from './reminders.ts';import * as alerts from './job-alerts.ts';import { authorizedCron } from '../autopilot/schedule.ts';
let client,admin,calls,run,email,push,options;
const owner='00000000-0000-4000-8000-000000000016';const jobId='00000000-0000-4000-8000-000000000017';const curve=createECDH('prime256v1');curve.generateKeys();
const device={id:'00000000-0000-4000-8000-000000000018',endpoint:'https://fcm.googleapis.com/send/fixture',p256dh:curve.getPublicKey().toString('base64url'),auth:Buffer.alloc(16,1).toString('base64url')};
const job={id:jobId,title:'React engineer',company_name:'Example',description:'Software engineering role.',location:'India remote',country:'India',employment_type:'full-time',seniority:'mid',salary_min:null,salary_max:null,salary_currency:'INR',skills:['React'],source:'himalayas',published_at:new Date().toISOString()};
function load(path){const routeModule=new Module(import.meta.filename);routeModule.require=name=>{if(name==='@/lib/operations/cron') return {monitoredCron:(_request,_worker,run)=>run()};if(name==='server-only')return {};if(name==='@/lib/supabase/server')return {createClient:async()=>client};if(name==='@supabase/supabase-js')return {createClient:()=>admin};if(name==='@/lib/notifications/reminders'||name==='./reminders')return reminders;if(name==='@/lib/notifications/job-alerts')return alerts;if(name==='@/lib/notifications/delivery')return load('./delivery.ts');if(name==='@/lib/autopilot/schedule')return {authorizedCron};if(name==='@/lib/matching/scorer')return {calculateMatchScore:()=>({score:80}),getResumeSkills:()=>['React']};if(name==='web-push')return {sendNotification:async(...args)=>push.push(args)};throw Error(name);};routeModule._compile(ts.transpileModule(readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,import.meta.filename);return routeModule.exports;}
const api=load('../../app/api/job-alerts/route.ts'),cron=load('../../app/api/cron/job-alerts/route.ts');
function setup(opts={}){options=opts;calls=[];run=null;email=[];push=[];for(const [k,v] of Object.entries({EMAIL_DELIVERY_ENABLED:'true',CRON_SECRET:'fixture',SUPABASE_SECRET_KEY:'fixture',NEXT_PUBLIC_SUPABASE_URL:'https://fixture.supabase.co',NEXT_PUBLIC_SITE_URL:'https://jobpilot.test',RESEND_API_KEY:'fixture',REMINDER_FROM_EMAIL:'reminders@example.com',VAPID_PUBLIC_KEY:'fixture',VAPID_PRIVATE_KEY:'fixture'}))process.env[k]=v;
 const user={id:owner,email:'candidate@example.com',email_confirmed_at:opts.unconfirmed?null:'2026-10-01'};
 function query(table){let filters={},mutation=null,fields;const q={select(value){fields=value;return q;},eq(k,v){filters[k]=v;return q;},in(k,v){filters[k]=v;return q;},is(k,v){filters[k]=v;return q;},gt(k,v){filters[k]=v;return q;},lte(){return q;},or(){return q;},order(){return q;},limit(){return q;},range(){return q;},upsert(value){mutation={type:'upsert',value};return q;},update(value){mutation={type:'update',value};return q;},delete(){mutation={type:'delete'};return q;},single:async()=>result(),maybeSingle:async()=>result(),then(resolve){resolve(result());}};
 function result(){calls.push({table,filters:{...filters},mutation});if(mutation){if(table==='job_alert_runs')run={...mutation.value};return {};}if(table==='account_deletion_requests')return {data:opts.deleting?{user_id:owner}:null};if(table==='job_alert_preferences')return {data:[{user_id:owner,email_enabled:true,push_enabled:true,enabled_at:new Date(Date.now()-86400000).toISOString()}]};if(table==='job_alert_runs')return {data:filters.run_day?run:null};if(table==='saved_searches')return {data:opts.noSearch?[]:[{criteria:{search:opts.noMatch?'Python':'React',minimumScore:70}}]};if(table==='profiles')return {data:{target_role:'Engineer',location:'India',experience_years:3}};if(table==='job_preferences')return {data:{minimum_match_score:70}};if(table==='resumes')return {data:{parsed_data:{}}};if(table==='moderated_jobs')return {data:fields==='id'?opts.hidden?[]:[{id:jobId}]:[job]};if(table==='push_subscriptions')return {data:[device]};return {data:null};}return q;}
 client={auth:{getUser:async()=>({data:{user:opts.signedOut?null:user}})},from:query};admin={from:query,auth:{admin:{getUserById:async()=>({data:{user}})}},rpc:async(name,args)=>{calls.push({rpc:name,args});assert.equal(name,'claim_job_alert');assert.equal(args.p_user,owner);return {data:opts.noClaim?[]:[{id:'delivery',attempts:2}]};}};
 return calls;}
const request=(body,origin='https://jobpilot.test')=>new Request('https://jobpilot.test/api/job-alerts',{method:'PATCH',headers:{Origin:origin},body:JSON.stringify(body)});
const cronRequest=(secret='fixture')=>new Request('https://jobpilot.test/api/cron/job-alerts',{headers:{Authorization:`Bearer ${secret}`}});
async function withEmail(work){const old=globalThis.fetch;globalThis.fetch=async(url,args)=>{assert.equal(url,'https://api.resend.com/emails');email.push(args);return new Response('{}',{status:options.emailFails?503:200});};try{await work();}finally{globalThis.fetch=old;}}
test('job alert preferences enforce auth, origin, strict opt-in and configured confirmed-email delivery',async()=>{setup({signedOut:true});assert.equal((await api.GET()).status,401);setup();assert.equal((await api.PATCH(request({email_enabled:true,push_enabled:false},'https://evil.test'))).status,403);assert.equal(calls.length,0);setup();assert.equal((await api.PATCH(request({email_enabled:true,push_enabled:false,user_id:'forged'}))).status,400);setup({unconfirmed:true});assert.equal((await api.PATCH(request({email_enabled:true,push_enabled:false}))).status,409);setup();assert.equal((await api.PATCH(request({email_enabled:true,push_enabled:false}))).status,200);assert.equal(calls.at(-1).mutation.value.user_id,owner);delete process.env.RESEND_API_KEY;delete process.env.VAPID_PRIVATE_KEY;assert.equal((await api.PATCH(request({email_enabled:false,push_enabled:false}))).status,200);});
test('worker skips unauthorized, deleting, unmatched, hidden and already claimed accounts',async()=>{setup();assert.equal((await cron.GET(cronRequest('wrong'))).status,401);assert.equal(calls.length,0);for(const opts of [{deleting:true},{noSearch:true},{noMatch:true},{hidden:true},{noClaim:true}]){setup(opts);await withEmail(async()=>{assert.equal((await cron.GET(cronRequest())).status,200);assert.equal(email.length,0);assert.equal(push.length,0);});}});
test('matching worker freezes owner digest, cursor and job IDs, separates channels and retries identical content',async()=>{setup();await withEmail(async()=>{let response=await cron.GET(cronRequest());assert.equal(response.status,200);assert.equal((await response.json()).sent,2);assert.deepEqual(run.job_ids,[jobId]);assert.deepEqual(JSON.parse(email[0].body).to,['candidate@example.com']);assert.ok(JSON.parse(email[0].body).text.includes(`/jobs/${jobId}`));assert.equal(JSON.parse(push[0][1]).kind,'jobs');const snapshot=run.digest;job.title='Changed title';response=await cron.GET(cronRequest());assert.equal(response.status,200);assert.equal(run.digest,snapshot);assert.equal(JSON.parse(email[1].body).text,snapshot);assert.equal(email[0].headers['Idempotency-Key'],email[1].headers['Idempotency-Key']);assert.ok(calls.filter(x=>x.table==='job_alert_deliveries').every(x=>x.filters.attempts===2));job.title='React engineer';});});
test('email failures do not suppress push; unconfirmed email is never sent',async()=>{setup({emailFails:true});await withEmail(async()=>{assert.equal((await cron.GET(cronRequest())).status,503);assert.equal(push.length,1);assert.ok(calls.some(x=>x.table==='job_alert_deliveries'&&x.mutation.value.status==='failed'));});setup({unconfirmed:true});await withEmail(async()=>{assert.equal((await cron.GET(cronRequest())).status,200);assert.equal(email.length,0);assert.equal(push.length,1);});});
