import test from 'node:test';import assert from 'node:assert/strict';import { Module } from 'node:module';import { readFileSync } from 'node:fs';import ts from 'typescript';import * as validation from './validation.ts';
let client,admin,calls;
function load(path){const routeModule=new Module(import.meta.filename);routeModule.require=name=>{if(name==='server-only')return {};if(name==='@/lib/supabase/server')return {createClient:async()=>client};if(name==='@supabase/supabase-js')return {createClient:()=>admin};if(name==='@/lib/recruiter/server')return load('./server.ts');if(name==='@/lib/recruiter/validation')return validation;throw Error(name);};routeModule._compile(ts.transpileModule(readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,import.meta.filename);return routeModule.exports;}
const recruiter=load('../../app/api/recruiter/route.ts'),jobs=load('../../app/api/recruiter/jobs/route.ts'),review=load('../../app/api/admin/company-verifications/route.ts'),verification=load('../../app/api/recruiter/verification/route.ts');
const owner='00000000-0000-4000-8000-000000000003',company='00000000-0000-4000-8000-000000000004',jobId='00000000-0000-4000-8000-000000000006';
function setup({signedIn=true,isAdmin=false,deleting=false,rpcError=null,hasCompany=true}={}){calls=[];process.env.SUPABASE_SECRET_KEY='fixture';process.env.NEXT_PUBLIC_SUPABASE_URL='https://fixture.supabase.co';client={auth:{getUser:async()=>({data:{user:signedIn?{id:owner,email:'owner@example.com',app_metadata:{role:isAdmin?'admin':'candidate'},user_metadata:{role:'admin'}}:null}})}};
admin={rpc:async(name,args)=>{calls.push({rpc:name,args});return {data:jobId,error:rpcError};},from(table){let filters={};const q={select(){return q;},eq(k,v){filters[k]=v;return q;},order(){return q;},limit(){return q;},range(){return q;},maybeSingle:async()=>result(),then(resolve){resolve(result());}};function result(){calls.push({table,filters:{...filters}});if(table==='account_deletion_requests')return {data:deleting?{user_id:owner}:null};if(table==='recruiter_companies')return {data:hasCompany?{id:company,user_id:owner}:null};return {data:[]};}return q;}};return calls;}
function request(body,method='POST',origin='https://jobpilot.test'){return new Request('https://jobpilot.test/api/recruiter',{method,headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});}
const companyBody={name:'Example Company',contact_name:'Example Recruiter',website:'https://example.com',evidence_url:'https://example.com/registration',details:'Registered business and authorized hiring representative.'};
const fields={title:'Software engineer',description:'Build and maintain useful software with a collaborative engineering team.',location:'India remote',country:'India',employment_type:'full-time',seniority:'senior',skills:['React'],salary_currency:'INR',application_url:'https://example.com/apply',posting_status:'draft'};
test('recruiter routes verify origin, fresh Auth, deletion freeze and admin role independently of user metadata',async()=>{
 setup();assert.equal((await recruiter.POST(request(companyBody,'POST','https://evil.test'))).status,403);assert.equal(calls.length,0);
 setup({signedIn:false});assert.equal((await recruiter.GET(new Request('https://jobpilot.test/api/recruiter'))).status,401);assert.equal(calls.length,0);
 setup({deleting:true});assert.equal((await jobs.POST(request({company_id:company,id:null,version:0,fields}))).status,409);assert.equal(calls.some(x=>x.rpc),false);
 setup();assert.equal((await review.GET(new Request('https://jobpilot.test/api/admin/company-verifications'))).status,403);assert.equal(calls.length,0);
 setup({isAdmin:true});assert.equal((await review.GET(new Request('https://jobpilot.test/api/admin/company-verifications?offset=-1'))).status,400);
});
test('onboarding, re-review and posting RPCs receive only authenticated owner identities and parsed fields',async()=>{
 setup();assert.equal((await recruiter.POST(request({...companyBody,user_id:'forged',verification_status:'verified'}))).status,201);let call=calls.find(x=>x.rpc);assert.equal(call.args.p_user,owner);assert.equal(call.args.p_domain,'example.com');assert.equal(call.args.p_verified,undefined);
 setup();assert.equal((await verification.POST(request({company_id:company,version:3,evidence_url:companyBody.evidence_url,details:companyBody.details}))).status,200);call=calls.find(x=>x.rpc);assert.equal(call.args.p_user,owner);assert.equal(call.args.p_version,3);
 setup();assert.equal((await jobs.POST(request({company_id:company,id:jobId,version:2,user_id:'forged',fields:{...fields,created_by:'forged',posting_status:'published'}}))).status,200);call=calls.find(x=>x.rpc);assert.equal(call.args.p_user,owner);assert.equal(call.args.p_version,2);assert.equal(call.args.p_fields.created_by,undefined);
 setup({rpcError:{message:'company_not_verified'}});assert.equal((await jobs.POST(request({company_id:company,id:jobId,version:2,fields:{...fields,posting_status:'published'}}))).status,409);
 setup({rpcError:{message:'posting_conflict'}});assert.equal((await jobs.POST(request({company_id:company,id:jobId,version:2,fields}))).status,409);
});
test('workspace reads are company/owner filtered and admin review binds actor plus version',async()=>{
 setup();assert.equal((await recruiter.GET(new Request('https://jobpilot.test/api/recruiter'))).status,200);assert.equal(calls.find(x=>x.table==='recruiter_companies').filters.user_id,owner);assert.equal(calls.find(x=>x.table==='jobs').filters.recruiter_company_id,company);assert.equal(calls.find(x=>x.table==='company_verification_requests').filters.user_id,owner);
 setup({isAdmin:true});assert.equal((await review.PATCH(request({id:company,version:1,decision:'approved',note:'Business and hiring authority verified',actor:'forged'},'PATCH'))).status,200);const call=calls.find(x=>x.rpc);assert.equal(call.args.p_admin,owner);assert.equal(call.args.p_version,1);
 setup({isAdmin:true});assert.equal((await review.PATCH(request({id:company,version:1,decision:'approved',note:'short'},'PATCH'))).status,400);assert.equal(calls.some(x=>x.rpc),false);
 setup();assert.equal((await recruiter.POST(request({...companyBody,details:'x'.repeat(65536)}))).status,400);assert.equal(calls.some(x=>x.rpc),false);
});
