import AppLayout from "@/app/(app)/layout";
import { CareerScene } from "@/components/career-scene";
import { ArrowUpRight, BriefcaseBusiness, FileText, CalendarClock, Bookmark, Search } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

export const dynamic = "force-dynamic";

export default async function DesignPreview({ searchParams }: { searchParams: Promise<{ view?: string }> }) {
  if (process.env.NODE_ENV !== "development") notFound();
  const { view = "dashboard" } = await searchParams;
  return <AppLayout><div className="mx-auto max-w-7xl px-4 py-6 sm:px-8">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3 border-b pb-4">
      <p className="text-xs text-muted-foreground">LOCAL DESIGN PREVIEW · Illustrative data · No account changes</p>
      <nav aria-label="Preview screens" className="flex flex-wrap gap-2">{["dashboard", "jobs", "applications", "resume", "recruiter"].map(key => <Link key={key} href={`/design-preview?view=${key}`} aria-current={view === key ? "page" : undefined} className="preview-tab rounded-lg border px-3 py-2 text-xs font-semibold">{key.charAt(0).toUpperCase() + key.slice(1)}</Link>)}</nav>
    </div>
    {view === "jobs" ? <>
      <header><p className="section-label">DISCOVER</p><h1 className="mt-2">Find your next chapter.</h1><p className="mt-3 text-sm text-muted-foreground">A focused workspace for comparing roles. These are illustrative cards, not vacancies.</p></header>
      <div className="my-6 flex min-h-12 items-center gap-3 rounded-xl border bg-card px-4 text-sm text-muted-foreground"><Search size={18} />Search roles, companies or skills</div>
      <div className="mb-5 flex flex-wrap gap-2" aria-label="Illustrative workplace filters">{["Any workplace", "Remote", "Hybrid", "On-site"].map(label => <span key={label} className="filter-pill">{label}</span>)}</div>
      <div className="job-results">{["Frontend engineer", "Product designer", "Data analyst"].map((role, index) => <article key={role} className="job-result-card p-5 sm:p-6"><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-secondary font-bold">{["S", "L", "T"][index]}</span><div className="flex-1"><p className="text-xs text-muted-foreground">Example company · Illustrative listing</p><h2 className="mt-1 text-lg font-semibold">{role}</h2><p className="mt-2 text-sm text-muted-foreground">Remote · Full time · Salary not provided</p></div><Bookmark size={19} /></div><div className="mt-5 flex flex-wrap gap-2">{["Role details", "Work preferences", "Compare the fit"].map(tag => <span key={tag} className="rounded-md bg-muted px-3 py-1 text-xs">{tag}</span>)}</div><div className="job-card-actions mt-4 flex flex-wrap items-center justify-between gap-3 border-t pt-4"><span className="text-xs text-muted-foreground">Illustrative listing · Not a live vacancy</span><Link href="/jobs" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-xs font-semibold text-primary-foreground">Explore real roles<ArrowUpRight size={16}/></Link></div></article>)}</div>
    </> : view === "applications" ? <>
      <header><p className="section-label">CAREER PIPELINE</p><h1 className="mt-2">Every next step, in sight.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Follow each opportunity from saved role to outcome. This board uses illustrative data; saved roles have not been submitted.</p></header>
      <div className="my-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-card p-4"><p className="text-sm text-muted-foreground">Clear stages. Visible reminders. One place to follow through.</p><Link href="/applications" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-xs font-semibold text-primary-foreground">Open your pipeline<ArrowUpRight size={16}/></Link></div>
      <section className="application-board" tabIndex={0} aria-label="Illustrative application pipeline. Scroll horizontally to see all stages">
        {[{stage:"Saved",description:"Considering · Not submitted",role:"Frontend engineer",company:"Example studio",next:"Review role & prepare"},{stage:"Applied",description:"Submission confirmed",role:"Product designer",company:"Example team",next:"Schedule a follow-up"},{stage:"Screening",description:"In review",role:"Data analyst",company:"Example company",next:"Review conversation notes"},{stage:"Interview",description:"Meeting the team",role:"Design engineer",company:"Example workspace",next:"Prepare for your interview"},{stage:"Offer",description:"Recorded outcome",role:"",company:"",next:""}].map(({stage,description,role,company,next}) => <div key={stage} className="pipeline-lane rounded-2xl border p-3"><div className="flex items-center justify-between px-1 pb-4"><div><h2 className="text-sm font-semibold">{stage}</h2><p className="mt-1 text-xs text-muted-foreground">{description}</p></div><span className="rounded-lg bg-card px-2 py-1 text-xs">{role ? "1" : "0"}</span></div>{role ? <article className="pipeline-card rounded-xl border bg-card p-4"><span className="grid size-9 place-items-center rounded-xl bg-secondary text-sm font-bold">{company.charAt(0)}</span><h3 className="mt-3 text-sm font-semibold">{role}</h3><p className="mt-1 text-xs text-muted-foreground">{company} · Illustrative</p><p className="mt-4 border-t pt-3 text-xs font-medium text-primary">{next}</p></article> : <p className="rounded-xl border border-dashed p-5 text-center text-xs text-muted-foreground">No illustrative offers</p>}</div>)}
      </section>
    </> : view === "resume" ? <>
      <header><p className="section-label">YOUR STORY</p><h1 className="mt-2">Make your experience count.</h1><p className="mt-3 text-sm text-muted-foreground">Your resume, versions and improvements, clearly organised.</p></header>
      <div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><section className="surface p-6"><span className="section-label">YOUR RESUME</span><h2 className="mt-3 text-xl font-semibold">Start with what you have.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Upload a resume, review its details and choose what to improve. Only your real experience belongs here.</p><Link href="/resume" className="jp-button mt-6 inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm text-primary-foreground"><FileText size={16} />Open your resume</Link></section><div className="rounded-2xl bg-secondary p-4"><CareerScene /></div></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-3">{["Experience", "Skills & projects", "Review & download"].map((label,index) => <section key={label} className="surface p-5"><span className="text-xs text-muted-foreground">0{index+1}</span><h2 className="mt-3 font-semibold">{label}</h2><p className="mt-2 text-sm text-muted-foreground">Review each part at your own pace.</p></section>)}</div>
    </> : view === "recruiter" ? <>
      <header><p className="section-label">HIRING WORKSPACE</p><h1 className="mt-2">Great teams start here.</h1><p className="mt-3 text-sm text-muted-foreground">Company, openings and candidate conversations in one place.</p></header>
      <section className="home-next-step mt-6"><div className="grid items-center gap-4 lg:grid-cols-2"><div><p className="section-label">YOUR NEXT STEP</p><h2 className="mt-3">Make a clear first impression.</h2><p className="mt-3 text-sm leading-6">Verify your company before publishing an opening. This preview does not create a company or job.</p><Link href="/recruiter" className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-900 px-4 text-sm text-white">Open hiring workspace<ArrowUpRight size={16} /></Link></div><CareerScene /></div></section>
      <div className="mt-6 grid gap-4 sm:grid-cols-3">{["Company & verification", "Openings & applicants", "Candidate conversations"].map(label => <section key={label} className="surface p-5"><BriefcaseBusiness className="mb-4 text-primary" size={22}/><h2 className="font-semibold">{label}</h2><p className="mt-3 text-sm text-muted-foreground">Clearly separated tasks, with privacy and consent preserved.</p></section>)}</div>
    </> : <>
      <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-label">YOUR WORKSPACE</p><h1 className="mt-2">A little focus. A big next step.</h1><p className="mt-3 text-sm text-muted-foreground">Your story, opportunities and progress—together.</p></div><span className="text-xs text-muted-foreground">Illustrative workspace</span></header>
      <section className="home-next-step mt-5"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="section-label">YOUR NEXT STEP</p><h2 className="mt-3">Find a role worth your time.</h2><p className="mt-3 text-sm leading-6">Explore openings, compare the fit and choose what feels right for your next chapter.</p><Link href="/jobs" className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-900 px-4 text-sm font-semibold text-white">Explore opportunities<ArrowUpRight size={16}/></Link></div><div className="dashboard-art"><CareerScene /></div></div></section>
      <nav aria-label="Your job search journey" className="journey-navigation mt-4 grid grid-cols-3 gap-2">{[{label:"Your story",Icon:FileText,href:"resume"},{label:"Discover",Icon:BriefcaseBusiness,href:"jobs"},{label:"Track progress",Icon:CalendarClock,href:"dashboard"}].map(({label,Icon,href},index) => <Link key={label} href={`/design-preview?view=${href}`} className="journey-stop flex items-center gap-3 rounded-xl px-3 py-3 text-xs font-semibold"><span className="journey-icon grid size-9 shrink-0 place-items-center rounded-xl"><Icon size={18}/></span><span><span className="mb-1 block text-[10px] text-muted-foreground">0{index+1}</span>{label}</span></Link>)}</nav>
      <div className="dashboard-stats mt-5 grid gap-4">{["Opportunities", "Saved roles", "Applications", "Interviews"].map(label => <section key={label} className="dashboard-stat"><span className="text-xs text-muted-foreground">{label}</span><p className="mt-3 text-3xl font-semibold">—</p><p className="mt-2 text-xs text-muted-foreground">Connect your real search</p></section>)}</div>
      <div className="mt-6 grid gap-6 lg:grid-cols-[1.5fr_1fr]"><section className="surface p-6"><p className="section-label">DISCOVERY</p><h2 className="mt-3 text-xl font-semibold">Room for possibilities.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Your real matches will appear here. The layout keeps discovery separate from tasks that need your attention.</p><Link href="/design-preview?view=jobs" className="mt-4 inline-block text-sm font-semibold text-primary">Preview role cards →</Link></section><section className="surface p-6"><p className="section-label">YOUR PLAN</p><h2 className="mt-3 text-xl font-semibold">One thing at a time.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Your actual follow-ups, preparation and saved learning work stay in the real dashboard.</p></section></div>
    </>}
  </div></AppLayout>;
}
