"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
export function AdminPlanControl({user}:{user:string}) {
 const [data,setData]=useState<{plan:{id:string;name:string;expires_at:string|null};catalog:{id:string;name:string}[]}|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false);const lock=useRef(false);
 useEffect(()=>{const controller=new AbortController();void fetch(`/api/admin/plans?user_id=${user}`,{cache:"no-store",signal:controller.signal}).then(async r=>{const v=await r.json();if(!r.ok)throw Error(v.error);setData(v);setError("");}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[user,revision]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current||!data)return;const form=new FormData(e.currentTarget);if(!window.confirm("Assign complimentary access? No payment or subscription is created; expiry restores free limits."))return;lock.current=true;setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/admin/plans",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:user,expected_plan:data.plan.id,plan:form.get("plan"),days:Number(form.get("days")),reason:form.get("reason")})});const v=await r.json();if(!r.ok)throw Error(v.error);setNotice("Complimentary plan assignment audited.");setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 return <form onSubmit={save} className="mt-4 rounded-xl border p-4"><h3 className="font-semibold">Complimentary plan access</h3><p className="mt-2 text-sm">Current: {data?.plan.name||"Loading…"}{data?.plan.expires_at&&` · expires ${new Date(data.plan.expires_at).toLocaleString()}`}. No payment or renewal.</p>{error&&<p role="alert" className="mt-2 text-destructive">{error}</p>}{notice&&<p role="status" className="mt-2">{notice}</p>}{data&&<fieldset disabled={busy} className="mt-3 space-y-3"><label className="block text-sm">Plan<select name="plan" key={data.plan.id} defaultValue={data.plan.id} className="ml-2 rounded border bg-background p-2"><option value="free_launch">Free launch</option>{data.catalog.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="block text-sm">Duration in days<input name="days" type="number" required min={1} max={90} defaultValue={30} className="ml-2 w-20 rounded border p-2"/></label><label className="block text-sm">Reason<textarea name="reason" required minLength={10} maxLength={1000} rows={2} className="mt-1 w-full rounded border p-2"/></label><Button type="submit">Assign complimentary access</Button></fieldset>}</form>;
}
