'use client';
import Link from 'next/link';
import { Dialog } from '@base-ui/react/dialog';
import { createClient } from '@/lib/supabase/client';
import { useCallback,useEffect,useRef,useState,type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
type Application={id:string;job_id:string;job_title:string;company_name:string;status:string;shortlisted:boolean;version:number;submitted_at:string};
type Resume={id:string;file_name:string;is_primary:boolean};
type Preview={resume:{file_name:string;raw_text:string;updated_at:string};profile:{full_name:string;target_role:string;location:string;updated_at:string};job:{title:string;company_name:string;version:number};account_email:string};
type Activity={id:string;actor:string;status:string;shortlisted:boolean;note:string;created_at:string};
export function HiringApplications({jobId}:{jobId?:string}){
  const [applications,setApplications]=useState<Application[]>([]),[resumes,setResumes]=useState<Resume[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[offset,setOffset]=useState(0),[hasMore,setHasMore]=useState(false);
  const [resume,setResume]=useState(''),[note,setNote]=useState(''),[contact,setContact]=useState(false),[confirmed,setConfirmed]=useState(false),[history,setHistory]=useState<{id:string;events:Activity[];has_more:boolean}|null>(null);const lock=useRef(false);const [preview,setPreview]=useState<Preview|null>(null);
  const load=useCallback(async()=>{const params=new URLSearchParams({offset:String(offset)});if(jobId)params.set('job_id',jobId);const response=await fetch(`/api/hiring-applications?${params}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);setApplications(data.applications);setResumes(data.resumes);setHasMore(data.has_more);setReady(true);},[jobId,offset]);
  useEffect(()=>{let stopped=false;(async()=>{try{const params=new URLSearchParams({offset:String(offset)});if(jobId)params.set('job_id',jobId);const response=await fetch(`/api/hiring-applications?${params}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);if(!stopped){setApplications(data.applications);setResumes(data.resumes);setHasMore(data.has_more);setReady(true);setError('');}}catch(cause){if(!stopped)setError((cause as Error).message);}})();return()=>{stopped=true;};},[jobId,offset]);
  async function mutate(body:unknown,method:string,notice:string){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/hiring-applications',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error);setMessage(notice);setHistory(null);await load();if(method==='POST'){setNote('');setConfirmed(false);setPreview(null);}}catch(cause){setError((cause as Error).message);}finally{lock.current=false;setBusy(false);}}
  async function activity(id:string,before?:string){setError('');try{if(!before)await load();const params=new URLSearchParams({id});if(before)params.set('before',before);const response=await fetch(`/api/hiring-applications/history?${params}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);setHistory(previous=>({id,events:before&&previous?.id===id?[...previous.events,...data.events]:data.events,has_more:data.has_more}));}catch(cause){setError((cause as Error).message);}}
  useEffect(()=>{const client=createClient();let stopped=false;let channel:ReturnType<typeof client.channel>|undefined;
    void client.auth.getUser().then(({data})=>{if(stopped||!data.user)return;channel=client.channel('candidate-hiring-updates').on('postgres_changes',{event:'UPDATE',schema:'public',table:'employer_applications',filter:`user_id=eq.${data.user.id}`},()=>{if(stopped||lock.current)return;setMessage('Your application has an update. Open activity to see the details.');void load().catch(cause=>setError(cause.message));}).subscribe();}).catch(()=>{if(!stopped)setMessage('Automatic updates unavailable. Use View activity to refresh.');});
    return()=>{stopped=true;if(channel)void client.removeChannel(channel);};
  },[load]);
  async function review(event?:FormEvent){event?.preventDefault();setBusy(true);setError('');setConfirmed(false);try{const response=await fetch(`/api/hiring-applications?${new URLSearchParams({job_id:jobId!,preview_resume:resume})}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);setPreview(data);}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
  function submit(){if(!preview||!confirmed)return;void mutate({job_id:jobId,resume_id:resume,cover_note:note,share_contact:contact,confirmed,review:{resume_updated_at:preview.resume.updated_at,profile_updated_at:preview.profile.updated_at,job_version:preview.job.version}},'POST','Application submitted to the verified employer.');}
  return <section className="rounded-2xl border bg-background p-5 sm:p-6"><h2 className="text-lg font-semibold">{jobId?'Apply within Parth Careers':'Applications sent through Parth Careers'}</h2><p className="mt-2 text-sm text-muted-foreground">Employer-confirmed stages appear here. Your private tracker notes and stages remain separate.</p>
    {error&&<p role="alert" className="mt-3 text-sm text-destructive">{error} <button className="underline" onClick={()=>void load().catch(cause=>setError(cause.message))}>Retry</button></p>}{message&&<p role="status" className="mt-3 text-sm">{message}</p>}
    {!ready&&!error&&<p className="mt-3 text-sm">Loading applications…</p>}
    {jobId&&ready&&applications.length===0&&<form onSubmit={review} className="mt-4 space-y-4"><fieldset disabled={busy} className="space-y-4">
      <label className="block text-sm">Resume to share<select required value={resume} onChange={e=>{setResume(e.target.value);setConfirmed(false);}} className="mt-1 w-full rounded-lg border bg-background p-2"><option value="">Select a saved resume</option>{resumes.map(r=><option key={r.id} value={r.id}>{r.file_name}{r.is_primary?' · Primary':''}</option>)}</select></label>
      {resumes.length===0&&<Link href="/resume" className="text-sm underline">Upload a resume first</Link>}
      <p className="text-xs text-muted-foreground">Shares the selected resume’s extracted text, your name, role and location. Resume text may already contain contact details. The original PDF and private notes stay private. <Link href="/resume" className="underline">Review your resume</Link> before confirming.</p>
      <label className="block text-sm">Cover note (optional)<textarea value={note} maxLength={4000} rows={4} onChange={e=>{setNote(e.target.value);setConfirmed(false);}} className="mt-1 w-full rounded-lg border bg-background p-2"/></label>
      <label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={contact} onChange={e=>{setContact(e.target.checked);setConfirmed(false);}}/>Share my confirmed account email with this employer</label>
      <Button type="submit" disabled={!resume}>Review application</Button>
    </fieldset></form>}
    {ready&&!jobId&&!applications.length&&<p className="mt-4 text-sm text-muted-foreground">No direct applications yet. Apply on a verified Parth Careers listing.</p>}
    <div className="mt-4 space-y-4">{applications.map(a=><article key={a.id} className="rounded-xl border p-4"><h3 className="font-semibold">{a.job_title} · {a.company_name}</h3><p className="mt-1 text-sm">Employer stage: {a.status}{a.shortlisted?' · Shortlisted':''}</p><p className="mt-1 text-xs text-muted-foreground">Submitted {new Date(a.submitted_at).toLocaleString()}</p><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>void activity(a.id)}>View activity / refresh updates</Button>{a.status!=='withdrawn'&&<Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Withdraw this application? Employer access to your shared resume, email and cover note will be removed.'))void mutate({id:a.id,version:a.version,confirmation:'WITHDRAW'},'PATCH','Application withdrawn. Shared resume and contact access removed.');}}>Withdraw</Button>}</div>
      {history?.id===a.id&&<div className="mt-4 space-y-3">{history.events.map(e=><div key={e.id} className="border-t pt-3 text-sm"><p>{e.actor} · {e.status}{e.shortlisted?' · Shortlisted':''} · {new Date(e.created_at).toLocaleString()}</p><p className="whitespace-pre-wrap break-words text-muted-foreground">{e.note}</p></div>)}{history.has_more&&<Button variant="outline" onClick={()=>void activity(a.id,String(history.events.at(-1)!.id))}>Older activity</Button>}</div>}
    </article>)}</div>
    {!jobId&&ready&&<div className="mt-4 flex gap-2"><Button variant="outline" disabled={busy||offset===0} onClick={()=>{setReady(false);setHistory(null);setOffset(Math.max(0,offset-50));}}>Previous</Button><Button variant="outline" disabled={busy||!hasMore} onClick={()=>{setReady(false);setHistory(null);setOffset(offset+50);}}>Next</Button></div>}
    <Dialog.Root open={!!preview} onOpenChange={open=>{if(!open&&!busy)setPreview(null);}}><Dialog.Portal><Dialog.Backdrop className="fixed inset-0 z-[60] bg-black/40"/><Dialog.Popup className="fixed left-1/2 top-1/2 z-[61] max-h-[90dvh] w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-2xl border bg-background p-5">
      <Dialog.Title className="font-semibold">Review before submitting</Dialog.Title><Dialog.Description className="mt-2 text-sm">These details will be shared with {preview?.job.company_name} for {preview?.job.title}.</Dialog.Description>
      {preview&&<><p className="mt-3 text-sm">{preview.profile.full_name} · {preview.profile.target_role} · {preview.profile.location}</p><p className="mt-2 text-sm">{contact?preview.account_email:'Account email not shared'}</p><h3 className="mt-3 text-sm font-semibold">{preview.resume.file_name} — extracted resume text</h3><pre className="mt-2 max-h-64 overflow-y-auto whitespace-pre-wrap break-words font-sans text-sm">{preview.resume.raw_text}</pre><p className="mt-3 whitespace-pre-wrap break-words text-sm">{note||'No cover note'}</p></>}
      {error&&<p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}
      <label className="mt-3 flex min-h-11 items-center gap-2 text-sm"><input disabled={busy} type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed these details and agree to share this application.</label><div className="mt-3 flex flex-wrap gap-2"><Button disabled={busy||!confirmed} onClick={submit}>Confirm & submit</Button><Button disabled={busy} variant="outline" onClick={()=>void review()}>Refresh review</Button><Dialog.Close disabled={busy} className="rounded-lg border px-3 py-2 text-sm">Back to draft</Dialog.Close></div>
    </Dialog.Popup></Dialog.Portal></Dialog.Root>
  </section>;
}
