import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { Module } from "node:module";
import ts from "typescript";
import { authorizedCron } from "../autopilot/schedule.ts";
import * as status from "./status.ts";
let calls = [], beginError = false, finishError = false, overlap = false;
const admin = { rpc: async (name, args) => {
  calls.push({ name, args });
  return name === "begin_worker_run" ? { data: overlap ? null : "run-id", error: beginError } : { data: !finishError, error: finishError };
} };
const routeModule = new Module(import.meta.filename);
routeModule.require = name => {
  if (name === "server-only") return {};
  if (name === "@supabase/supabase-js") return { createClient: () => admin };
  if (name === "@/lib/autopilot/schedule") return { authorizedCron };
  if (name === "./status") return status;
  throw Error(name);
};
routeModule._compile(ts.transpileModule(readFileSync(new URL("./cron.ts", import.meta.url), "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, import.meta.filename);
const { monitoredCron } = routeModule.exports;
test("cron monitoring denies unauthorized/overlapping/unrecorded work and records only safe aggregates", async () => {
  process.env.CRON_SECRET = "private-secret"; process.env.SUPABASE_SECRET_KEY = "private-key"; process.env.NEXT_PUBLIC_SUPABASE_URL = "https://fixture.supabase.co";
  let ran = 0;
  const request = (secret = "private-secret") => new Request("https://jobpilot.test/api/cron/reminders", { headers: { Authorization: `Bearer ${secret}` } });
  const work = async () => { ran++; return Response.json({ sent: 2, failed: 0, error: "private message", token: "secret" }); };
  assert.equal((await monitoredCron(request("wrong"), "reminders", work)).status, 401); assert.equal(calls.length, 0); assert.equal(ran, 0);
  beginError = true;
  assert.equal((await monitoredCron(request(), "reminders", work)).status, 503); assert.equal(ran, 0);
  beginError = false; overlap = true;
  assert.equal((await monitoredCron(request(), "reminders", work)).status, 409); assert.equal(ran, 0);
  overlap = false; calls = [];
  assert.equal((await monitoredCron(request(), "reminders", work)).status, 200);
  assert.deepEqual(calls[1].args, { p_id: "run-id", p_state: "succeeded", p_completed: 2, p_failed: 0, p_skipped: 0 });
  assert.ok(!JSON.stringify(calls).includes("private"));
  calls = [];
  assert.equal((await monitoredCron(request(), "reminders", async () => { throw Error("private content"); })).status, 503);
  assert.equal(calls[1].args.p_state, "failed");
  finishError = true;
  assert.equal((await monitoredCron(request(), "reminders", work)).status, 503);
});
